numpy- for scientif calculation,maths
array and vector

In [ ]:
import numpy as np
#creating arry
#1d array
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))  ##nd array(n dimension array)
print(arr.shape)  #(5,)means single dimension

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)
 #2d array 1row 5 col

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [4]:
arr2.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [5]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
#2d array
arr2=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)


In [8]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
##identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(a)
print(a.shape)
print(a.ndim) #num of dimension
print(a.size) #number of elements
print(a.dtype) # data type

print(a.itemsize) #item size in bytes

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)
2
10
int64
8


### numpy vectorized operation

In [ ]:
#elemnt wise addition
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])

print(a+b)

[11 22 33 44]


In [14]:
print(a-b)
print(a*b)
print(a/b)


[ -9 -18 -27 -36]
[ 10  40  90 160]
[0.1 0.1 0.1 0.1]


In [15]:
#universal function---applies to entire array
a=np.array([1,2,3,4])
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.        ]


In [16]:
print(np.exp(a))
print(np.sin(a))
print(np.log(a))

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]


In [18]:
##Slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
print(arr[0][2])

3


In [21]:
print(arr[0])

[1 2 3 4]


In [23]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [24]:
arr[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [29]:
##Normalization
##mean to 0 and deviation to 1
arr=np.array([1,2,3,4,5])
mean=np.mean(arr)
stdev=np.std(arr)

normalized_data=(arr-mean)/stdev
print(normalized_data)

median=np.median(arr)
print(median)
var=np.var(arr)
print(var)



[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
3.0
2.0


In [ ]:
##Logical operation
data=np.array([1,2,3,4,5,6,7,8,9])
data>5
#for index
data[data>5]

#logical and or----> & |

array([6, 7, 8, 9])

In [36]:
arr=np.array([1,2,"sans"])
print(arr)
print(len(arr))

['1' '2' 'sans']
3
