In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
from sklearn.datasets import make_classification
#creating datasets

In [8]:
## create the dataset
X ,y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=15)
#10 independent feature
#2 outputs(n_classes)
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0   -0.377957  1.043895  1.043494 -0.101838 -1.617442  0.402713  0.913601   
1   -0.325259  1.276263 -0.686123 -2.463205 -0.489426 -0.240715 -1.469496   
2    0.739019 -0.600903 -0.177294  1.335714 -0.817332 -0.790047  1.457365   
3    0.474312 -1.103002  1.189936 -0.800186  0.912377 -0.406451 -1.130950   
4    0.927365  1.114796  0.080284  1.261064  0.761179  0.921563  0.440832   
..        ...       ...       ...       ...       ...       ...       ...   
995  1.538272  0.171629  0.075371 -0.957658 -1.066219  1.158096 -0.036964   
996 -0.060266  0.095018 -0.271685  1.830560  0.219445 -0.341269  1.180088   
997  0.675563 -0.538420 -1.299500  0.747835  1.733898 -0.268044 -0.520953   
998  2.629710 -2.452899 -1.359785  1.592065  0.854157  1.618828  0.621701   
999 -1.791491 -0.121908  0.535153 -0.588085 -1.929461 -0.659900  0.754921   

            7         8         9  
0   -0.067192  0.175471 -1.049646  
1    1.006633 -0.833692  0.957744  
2   -0.218981  0.878643 -1.257740  
3    1.985111  1.379029  1.041768  
4    0.184645 -1.567739 -0.142107  
..        ...       ...       ...  
995  0.123689  0.927871 -0.225003  
996 -0.216876 -1.752938 -0.810152  
997  2.043336  0.947388  0.790354  
998  0.378898 -1.971894 -0.252250  
999 -1.941357  0.589002 -1.007482  

[1000 rows x 10 columns]

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split( X,y,test_size=0.30,random_state=42)

In [9]:
#model training
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()
logistic.fit(X_train,y_train)
y_pred=logistic.predict(X_test)
print(y_pred)

[0 0 0 1 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 0 0 0 0 1 1 0 1 1 1 0 1
 1 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0
 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 1 1 1 0 1 1 1 0 1 1 1 1 0 0 0 0 0 1 0 0 0 1
 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 1 1 0 0 0 1 1
 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 0 0 1 0 1 1 0 1 1 0 0 1 1 0 1 0 1 0
 0 1 1 0 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 0 0 1 0 1 0 1 1 0 1 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 1 0 0 1 1 0 1 1 0 0 1 0 0 1
 0 0 1 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 0 1
 0 1 0 0]


In [12]:
logistic.predict_proba(X_test)


array([[9.33115111e-01, 6.68848891e-02],
       [6.60305264e-01, 3.39694736e-01],
       [8.65366570e-01, 1.34633430e-01],
       [9.60311284e-02, 9.03968872e-01],
       [2.43186448e-01, 7.56813552e-01],
       [5.76341649e-01, 4.23658351e-01],
       [8.25099409e-01, 1.74900591e-01],
       [2.30396936e-04, 9.99769603e-01],
       [1.25509886e-02, 9.87449011e-01],
       [2.73700749e-03, 9.97262993e-01],
       [7.07020509e-03, 9.92929795e-01],
       [5.68080321e-01, 4.31919679e-01],
       [8.39012147e-02, 9.16098785e-01],
       [9.73831278e-01, 2.61687218e-02],
       [1.27555917e-02, 9.87244408e-01],
       [8.06171769e-01, 1.93828231e-01],
       [9.95120127e-01, 4.87987316e-03],
       [1.78752959e-02, 9.82124704e-01],
       [9.78694999e-01, 2.13050006e-02],
       [3.90586932e-02, 9.60941307e-01],
       [3.39280977e-02, 9.66071902e-01],
       [3.13931361e-02, 9.68606864e-01],
       [5.01016525e-02, 9.49898348e-01],
       [8.18498841e-01, 1.81501159e-01],
       [8.589143

In [13]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [15]:
score=accuracy_score(y_test,y_pred)
print(score)
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

0.9166666666666666
              precision    recall  f1-score   support

           0       0.93      0.91      0.92       160
           1       0.90      0.92      0.91       140

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

[[146  14]
 [ 11 129]]


### HyperParameter tuning and CV


# GRIDSEARCH CV

In [16]:
model=LogisticRegression()
penalty=['l1', 'l2', 'elasticnet']  #ridge lasso elastic net
c_values=[100,10,1.0,0.1,0.01]
solver=['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'] #algoeithim for optimization of problems 'liblinear for small datasets. 'sag and saga for large ones.  

In [20]:
#convertig to key vallue pair
dict(penalty=penalty,C=c_values,solver=solver)

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1.0, 0.1, 0.01],
 'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']}

In [21]:
params=dict(penalty=penalty,C=c_values,solver=solver)

In [22]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

In [23]:
## GridSearchCV
from sklearn.model_selection import GridSearchCV

grid=GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)

In [24]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [ ]:
# this will find the best parameters for our model
grid.fit(X_train,y_train)

c:\Users\Hp\Desktop\aiml\venv\lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Hp\Desktop\aiml\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Hp\Desktop\aiml\venv\lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\Hp\Desktop\aiml\venv\lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, se

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [26]:
#to see the best parameters
grid.best_params_

{'C': 0.01, 'penalty': 'l1', 'solver': 'saga'}

In [27]:
grid.best_score_

np.float64(0.9242857142857142)

In [28]:
y_pred=grid.predict(X_test)

In [29]:
score=accuracy_score(y_pred,y_test)
print(score)
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

0.92
              precision    recall  f1-score   support

           0       0.95      0.90      0.93       165
           1       0.89      0.94      0.91       135

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

[[149  16]
 [  8 127]]


# Randomized SeaechCv 
takes less time than gridparam as it takes sample of our model and train the model.
it picks random parameters and random attributes

In [30]:
from sklearn.model_selection import RandomizedSearchCV

In [31]:
model=LogisticRegression()
randomcv=RandomizedSearchCV(estimator=model,param_distributions=params,cv=5,scoring='accuracy')

In [32]:
randomcv.fit(X_train,y_train)

c:\Users\Hp\Desktop\aiml\venv\lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
20 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Hp\Desktop\aiml\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Hp\Desktop\aiml\venv\lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\Hp\Desktop\aiml\venv\lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [33]:
randomcv.best_score_

np.float64(0.9242857142857142)

In [34]:
randomcv.best_params_

{'solver': 'saga', 'penalty': 'l1', 'C': 0.01}

In [35]:
y_pred=randomcv.predict(X_test)

In [36]:
score=accuracy_score(y_pred,y_test)
print(score)
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

0.92
              precision    recall  f1-score   support

           0       0.95      0.90      0.93       165
           1       0.89      0.94      0.91       135

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

[[149  16]
 [  8 127]]
